CREATE TABLE IF NOT EXISTS SCHEDULER
(
    SCHEDULER_ID BIGINT AUTO_INCREMENT PRIMARY KEY comment 'SCHEDULER의 고유 식별자',
    WRITER VARCHAR(30) NOT NULL comment '작성자명',
    PASSWORD VARCHAR(20) NOT NULL comment '비밀번호',
    SCHEDULE VARCHAR(400) comment '할 일',
    CREATION_DATE TIMESTAMP comment '최초 작성일',
    MODIFICATION_DATE TIMESTAMP comment '수정일'
);
